title: Guldräber
email: kontakt@guldraeber.de
description: >-
    Die Guldräber - angeführt von Andi dem Großen Genialen Guldräber - sind eine internationale Sekte von
    Informatikern, Mathematikern, Ingeniören, Physikern und anderen Wichtigtuern, die sich zusammengeschlossen haben,
    um Böses zu bekämpfen, Gutes zu tun und sich über irrelevante und irr relevante Dinge zu beschweren.
url: "https://guldraeber.de"

# Build settings
markdown: kramdown
highlighter: pygments
plugins:
  - jekyll-feed

sass:
  style: compressed

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - s3_website.yml
  - Rakefile
  - vendor
