baseURL = "https://guldraeber.de/"
languageCode = "de-de"
defaultContentLanguage = "de"
title = "Guldräber"
enableGitInfo = true
uglyurls = true

[[menu.main]]
identifier = "test"
name = "Der Guldräbertest"
url = "/test.html"